ALTER TABLE hospitals
DROP PRIMARY KEY,
DROP COLUMN my_row_id,
MODIFY id INT NOT NULL AUTO_INCREMENT,
ADD PRIMARY KEY (id);

ALTER TABLE receivers
DROP PRIMARY KEY,
DROP COLUMN my_row_id,
MODIFY id INT NOT NULL AUTO_INCREMENT,
ADD PRIMARY KEY (id);

ALTER TABLE bloodinfo
DROP PRIMARY KEY,
DROP COLUMN my_row_id,
MODIFY bid INT NOT NULL AUTO_INCREMENT,
ADD PRIMARY KEY (bid);

ALTER TABLE bloodrequest
DROP PRIMARY KEY,
DROP COLUMN my_row_id,
MODIFY reqid INT NOT NULL AUTO_INCREMENT,
ADD PRIMARY KEY (reqid);

ALTER TABLE blooddonate
DROP PRIMARY KEY,
DROP COLUMN my_row_id,
MODIFY donoid INT NOT NULL AUTO_INCREMENT,
ADD PRIMARY KEY (donoid);

ALTER TABLE blooddinfo
DROP PRIMARY KEY,
DROP COLUMN my_row_id,
MODIFY bdid INT NOT NULL AUTO_INCREMENT,
ADD PRIMARY KEY (bdid);
